### ISSUE TITLE
Can't finish running

### ISSUE THREAD

**Issue by torn4dom4n** [msiniscalchi/atom-latextools#113]
Can not finish running if file doesn't have `\end{document}`

**Comment by ig0774** [comment]
Can you be a bit clearer about what the issue is? LaTeX requires both a `\begin{document}` and an `\end{document}` or else it won't build. However, there's no specific requirement that either of these be in the same file, as long as they're `\include`'d or `\input` at the appropriate location.

**Comment by torn4dom4n** [comment]
I had tested your package with this code:
```
\documentclass[12pt,a4paper]{article}
\usepackage[utf8]{vietnam}
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage[left=2cm,right=2cm,top=2cm,bottom=2cm]{geometry}

\begin{document}
\noindent
Bất đẳng thức Cauchy: với $x_1,x_2,\ldots,x_n\geq 0$, ta có:
$\dfrac{x_1 +x_2+\ldots+x_n}{n}\geq \sqrt[n]{x_1 x_2\ldots x_n}$
end{document}
```

**Comment by torn4dom4n** [comment]
![latextools](https://cloud.githubusercontent.com/assets/16760489/17431519/a1350a9e-5b24-11e6-9855-b33fdead9f18.png)

**Comment by torn4dom4n** [comment]
When I ran code, LaTextools can't finish it and it don't show error.

**Comment by ig0774** [comment]
Ah, yes, I see what you're referring to. It seems `-b` on TeXify [implies `--interaction=scrollmode`](https://github.com/MiKTeX/miktex/blob/b62a1e7/Programs/MiKTeX/texify/mcd.cpp#L1439) rather than `--interaction=nonstopmode` or `--interaction=batchmode`. Bizarrely, for some reason I can't determine, running [the exact same command from the Sublime version](https://github.com/SublimeText/LaTeXTools/blob/c6b64b88f52f9e3994ff08017f4e78ae05fb3cb9/builders/traditionalBuilder.py#L17) does not produce the same behaviour, i.e., TeXify at least quits. In any case this should be easy enough to fix.
