### ISSUE TITLE
pdf-view refreshes repeatdetly

### ISSUE THREAD

**Issue by eladrich** [msiniscalchi/atom-latextools#126]
When compiling the latex project, the pdf-view reloads the pdf and then keeps refreshing for almost a minute, reloading the same document again and again.

**Comment by ig0774** [comment]
This is presumably an issue with `pdf-view` rather than this plugin. I think `pdf-view` reloads the document when the file is updated... Is it possible you have a different program modifying the PDF? Is the PDF in a normal directory or a Dropbox directory (or other similar software) or on a remote share?

**Comment by eladrich** [comment]
You are right, issue isn't related to latextools.
