### ISSUE TITLE
Multiple PDF refreshes

### ISSUE THREAD

**Issue by guyhoffman** [msiniscalchi/atom-latextools#148]
Every time I run Latextools > Build using the pdf-view preview, the PDF window refreshes between 3-6 times. If I use an external viewer (Skim) this doesn't happen. It might be an issue with pdf-view or with latextools, but I thought I'd start here.

**Comment by ig0774** [comment]
This is behaviour in `pdf-view`, which is reloading the file when it is updated on disk, which happens during the TeX compilation process. (Incidentally, by default Skim does this too, but it's reloading is substantially faster). LaTeXTools only tells `pdf-view` to reload the file once the compilation is complete. I'm not sure anything can be done from the LaTeXTools side to disable this reloading behaviour.

**Comment by schlichtanders** [comment]
If LaTexTools is using pdflatex (or something similar) for compilation, this can be addressed within LaTexTools. pdflatex has the flag ``-jobname`` to change the output filename.

One could simply output to a tempory filename during the compilation pipeline and copy it back afterwards to the original filename. (Or if it is known which compilation step is the last one, you can of course directly compile the last one to the correct filename). Sounds like an easy fix to me.

I even think this behaviour might be best addressed within LaTexTools as the Reload-On-File-Change behaviour of the pdf viewers is a very wanted feature.

**Comment by ig0774** [comment]
@schlichtanders: Something like that could be made to work, but it's not a trivial solution.

* On MiKTeX on Windows latextools uses `texify` (the MiKTeX compiler driver), since it's installed by default. `texify` doesn't support `-jobname`, so we'd need to work around that. The simplest thing is to create a copy of the `.tex` file and change the name of that, etc.; this, however, would likely break synctex. Somewhat more complexly, we could implement something that just calls `pdflatex` and friends but supports jobname. Something like this is in the pipeline but hasn't yet been implemented.

* The `jobname` parameter sets the `\jobname` primitive, which may be used inside the document (a common idiom is something like `\bibliography{\jobname}`), so hijacking the `jobname` for this feature could result in latextools being unable to compile correctly.

**Comment by schlichtanders** [comment]
Users on Windows can also use texlive, hence it might be a valid option to implement this feature for texlive distributions only (at least for now).

This of course does not address your second point. It is a bit a weird that a commandline option overwrites a variable within the latex file... For my intuition this should not happen at all.
