### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/michelmooij/TEX-bestanden/Templat...

### ISSUE THREAD

**Issue by mooij009** [msiniscalchi/atom-latextools#28]
[Enter steps to reproduce below:]

I try to compile a letter with pstricks signature. It works in TeXshop using xelatex

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.3
**Thrown From**: [latextools](https://github.com/msiniscalchi/atom-latextools) package, v0.7.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/michelmooij/TEX-bestanden/Templates/Brief.log'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/Users/michelmooij/TEX-bestanden/Templates/Brief.log'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at /Users/michelmooij/.atom/packages/latextools/lib/builder.coffee:155:18
    at ChildProcess.exithandler (child_process.js:222:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -7:45.3.0 latextools:build (atom-text-editor.editor.is-focused)
     -4:02.8.0 latex:build (atom-text-editor.editor.is-focused)
     -3:29.2.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -2:46.8.0 latextools:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -2:40.2.0 latextools:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "native-ui",
      "one-light-syntax"
    ]
  },
  "latextools": {
    "builder": "latex",
    "builderSettings": {
      "displayLog": true,
      "options": [
        "-f"
      ]
    },
    "commandCompletion": "always",
    "darwin": {
      "texpath": "/Library/TeX/texbin"
    },
    "linux": {},
    "win32": {}
  }
}
```

### Installed Packages

```coffee
# User
language-latex, v0.6.1
latex, v0.28.2
latexer, v0.2.7
latextools, v0.7.4
markdown-preview-opener, v0.1.1
markdown-table-formatter, v2.7.2
native-ui, v0.16.1

# Dev
No dev packages
```

**Comment by msiniscalchi** [comment]
Two things. First, there is an odd configuration option: `"builder": "latex"`. The only supported option right now is `texify-latextools`. How did you set that? Second, you have the `latex` package. Can you try disabling that?

The error is thrown because the log file can't be found. This can only happen if compilation fails---that is, if `texify` or `latexmk` cannot run. There is slightly better error reporting in the current master branch; I still have to push the update though. In any case, this is usually a consequence of misconfiguration, which is what the first item above is about.

**Comment by mooij009** [comment]
I have changed builder to latexmk, but:
LaTeXTool Console:
ERROR 1:
123: 128: execution error: File "Macintosh HD: Users: michel mooij: TEX files: Boekje” can not be converted into type alias. (-1700)

**Comment by msiniscalchi** [comment]
The builder should be set to `texify-latexmk`. If you configure the package settings from the atom settings page (CMD-,), the *Builder* option has a drop-down menu with (for now) a single option, `texify-latexmk`. If you configure settings directly, make sure you give the right option.

**Comment by msiniscalchi** [comment]
@mooij009 is this still an issue, or can I close?

**Comment by mooij009** [comment]
My problem is not solved. 
I get ERROR 1 at the end of the compilation. The PDF file is not written.


Michel Mooij
Kortegracht 1c
3811 KG Amersfoort
0645480893

**Comment by ig0774** [comment]
You do need to tell LaTeXTools to use xelatex, which you can do using the "program" configuration setting. It should be set to "xelatex". Otherwise the default settings just run pdflatex.

**Comment by mooij009** [comment]
Thank you, it now works ,  except for PStricks.

Met vriendelijke groet,

Michel Mooij
+31645480893
Verstuurd vanaf mijn iPad

**Comment by ig0774** [comment]
Short answer: please just use the default `texpath` value `"/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin"`. 

Long answer: `texpath` basically exists because (recent versions of) OS X run GUI applications with a very impoverished environment: `$PATH` is `"/usr/bin:/bin:/usr/sbin:/sbin"` and the various methods to add more entries to the `$PATH` have been slowly disabled. `pstricks` requires access to various Ghostscript utilities that are (typically) installed in `/usr/local/bin` so, from the perspective of the Atom.io environment, they may as well not be installed. LaTeXTools gets around this by defining `texpath` to include other optional directories to add, but your config file never provided it with all the needed paths, hence, it doesn't generate a PDF (more specifically, if you care, when using raw postscript---as `pstricks` does---xetex generates an `xdv` file at the end of its processing and then uses `xdvipdfmx` to generate a `pdf`; the `xdv` file would be generate successfully but `xdvipdfmx` requires Ghostscript to turn the `xdv` file into a `pdf` file).

**Comment by mooij009** [comment]
Thanks a lot. It works fine now


Michel Mooij
Kortegracht 1c
3811 KG Amersfoort
0645480893


> Op 12 feb. 2016, om 13:23 heeft ig0774 <notifications@github.com> het volgende geschreven:
> 
> /Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin
